### ISSUE TITLE
Add Secure Web Socket support (wss)

### ISSUE THREAD

**Issue by itsabdessalam** [boxmetrics/boxmetrics-agent#33]
Implement WebSocket protocol over https

**Comment by l4u23n7p** [comment]
Hi @Abdessalam98 ! ✋ 

WSS is already implement in the agent. Nevertheless, to use it you need to have valid certificate for the agent. Currently, this step need to be done manualy and that's the purpose of #21 to automate it.

However, if you want to use WSS now, you can use helpers function present in `makefile`.

1. `make rootca`
2. `make cert`

Kings regards,

Laurent
